; PlatformIO Project Configuration File
[env:Espectrografo_AS7265X]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino
board_build.partitions = min_spiffs.csv
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
monitor_speed = 115200
lib_deps =
    sparkfun/SparkFun Spectral Triad AS7265X@^1.0.5
    esphome/ESPAsyncWebServer-esphome@^3.2.2
    esphome/AsyncTCP-esphome@^2.1.4
    arduino-libraries/SD@^1.2.4
    bblanchon/ArduinoJson@^7.2.1
